name: "Meeting Name"
description: "Buat jadwal meeting atau workshop baru"
labels: ["meeting", "workshop"]
body:
  - type: markdown
    attributes:
      value: |
        Formulir ini akan membuat file ICS secara otomatis.
  - type: input
    id: title
    attributes:
      label: "Judul Materi"
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Deskripsi"
      required: true
  - type: input
    id: date
    attributes:
      label: "Tanggal"
      placeholder: "DD-MM-YYYY"
      description: "Format: DD-MM-YYYY (Contoh: 25-12-2023)"
    validations:
      required: true
  - type: dropdown
    id: time
    attributes:
      label: "Jam Mulai (WIB)"
      options:
        - "19:00"
        - "19:30"
        - "20:00"
        - "20:30"
        - "21:00"
    validations:
      required: true
  - type: dropdown
    id: duration
    attributes:
      label: "Durasi"
      options:
        - "1 Jam"
        - "1.5 Jam"
        - "2 Jam"
    validations:
      required: true
